export const CATEGORIAS = [
  "Agência Coligada",
  "Alimentação e Doces",
  "Ativações Interativas",
  "Audiovisual",
  "Bebidas Private Label",
  "Beleza e Bem-estar",
  "Brindes e Kits",
  "Cenografia",
  "Chopp e Bebidas",
  "Confecção e Uniformes",
  "Conteúdo e Roteiro",
  "Efeitos Especiais",
  "Espaços para Eventos",
  "Estamparia",
  "Estruturas para Eventos",
  "Foto e Vídeo",
  "Games e Ativações",
  "Gráfica e Comunicação Visual",
  "Hotelaria",
  "Legalização e Seguros",
  "Limpeza e Segurança",
  "Locação de Equipamentos",
  "Mascotes e Fantasias",
  "Mídia e Publicidade",
  "Mobiliário e Decoração",
  "Música e Entretenimento",
  "Pisos e Coberturas",
  "Produção e Cerimonial",
  "Recreação e Festa Junina",
  "RSVP e Credenciamento",
  "Saúde e Emergência",
  "Som, Luz e Imagem",
  "Staff e Promotores",
  "Stands",
  "Talentos e Palestrantes",
  "Team Building",
  "Tradução e Acessibilidade",
  "Transporte e Logística",
  "Transporte Executivo",
  "Outros",
];

export const UFS = [
  "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS",
  "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC",
  "SP", "SE", "TO",
];
